# Generated by Django 3.0.8 on 2020-09-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comentor',
        ),
        migrations.AlterField(
            model_name='author',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
