# Generated by Django 3.0.8 on 2020-09-10 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0002_auto_20200911_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sadmin.Author'),
        ),
    ]
