# Generated by Django 3.0.8 on 2020-09-11 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0003_auto_20200911_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.Author'),
            preserve_default=False,
        ),
    ]
