# Generated by Django 3.0.8 on 2020-09-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0005_author_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
