# Generated by Django 3.0.8 on 2020-08-14 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0007_auto_20200809_1014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Surveyor',
            new_name='Author',
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sadmin.Category'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sadmin.Article'),
        ),
    ]
