# Generated by Django 3.0.8 on 2020-09-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0010_auto_20200918_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
